version: "3"

services:
  app:
    container_name: app
    build: .
    environment:
      - PORT=${PORT}
    ports:
      - "4005:4005"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
